services:
  node-app:
    image: ghusnmhsen/wizardry_wheels_ghusn
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1

      update_config:
        parallelism: 2
        delay: 10s

      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb-container
    volumes:
      - mongo-db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
volumes:
  mongo-db:
